### PR TITLE
Allowed for visibility to be specified for each constructor

### PR DESCRIPTION
**Pull request by jimbxb**
A few other changes are also present:
* fixed visibility for some procs
* improved error messages when fields of the same name have differing visibility/type
* clean up Normalisation. It is a bit of a mess and hard to maintain

### CODE REVIEW

**Review by pschachte — CHANGES_REQUESTED** [review]
Nice!  I always meant to support individual visibilities for constructors, but couldn't think of a good syntax.  This one is good.

Could you please document this in Wybe.md?

Also, could you please add a test case to ctor_visibility.wybe that has the `constructors` keyword without pub before it?  That should still be OK, but it's worth having an explicit test case.

**Comment by jimbxb** [comment]
Of course... Always the WYBE.md.

**Review by pschachte — CHANGES_REQUESTED** [review]
Also, please update WYBE.md to document the need for the `constructor` keyword in `type` declarations.

**Review by pschachte — APPROVED** [review]
Thank you!

**Pull request merged**
