### PR TITLE
Add a naive vscode plugin implementation

### PR DESCRIPTION
**Pull request by CaviarChen**
Related issue #122.

I think the existing version is using a legacy template. Mine is based on this guide: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

I tried some of the rules in the existing one but they don't work, so I just replaced them.

### CODE REVIEW

**Review by pschachte — CHANGES_REQUESTED** [review]
This looks really good, but can you please update the README.md file to add installation instructions?

**Comment by CaviarChen** [comment]
Sorry for getting back to this so late.
The guide can be found here: https://code.visualstudio.com/api/working-with-extensions/publishing-extension
If you want to publish this extension, maybe it is unnecessary to describe this in README?

**Comment by pschachte** [comment]
Oh, wow!   I had no idea how complicated it would be!   Yes, I definitely think there should be really simple instructions, hopefully along the lines of "copy this directory to such-and such a place and restart VS Code" or "run this command in the VS Code command palette".  I hope you don't have to install JavaScript and node.js just to get code colouring for Wybe code.  What did you have to do to test your extension?

**Comment by CaviarChen** [comment]
**For testing:**
Open folder `plugins/vscode` in vscode and press F5. A new vscode window will pop up with this extension enabled.

**For publishing it:**
I don't think it's a good idea to let users build the extension themselves, it requires node.js etc.
We can build and pack the extension into a `*.vsix` file, but it is still not that easy to use and we need to figure out a way to distribute the `.vsix` file.

I think the best approach is to publish this extension to vscode marketplace properly. The main job here is to create an account following that guide. If you don't mind, I can do that for you, but just that I'll have the control of it, or you can create it and give me a token or something, basically give me the permission to manage it in marketplace.
Once have the account, it is easy to build and publish (upgarde) the extension to vscode marketplace. I can run the command manually for now, just let me know when someone update the code for the extension.

I can also setup a github action to do the last step automatically, but since we won't change it frequently at least for now, that's something for the future.

**Pull request closed without merging**
